spring.application.name=payment-service
server.port=4011

# Stripe Configuration
stripe.webhook.secret=pk_test_51SUwipIoRR1TvgIGi3LZRpPQUZyTPHHprp4mu9zDpMa7bSUpbrXIjgApdPIn5pwdCat7duGJZpEqvihT4FHjtHgd00d4qrcMQG
stripe.api.key=sk_test_51SUwipIoRR1TvgIGNgdBjKMB5GQFWSFEwwc01kCQG2IeVC33SPlb8ZDWHQY3f6L67NKIR4Fc7mBfd4iM67XLBUg100IeeNX84b

# Database Configuration
spring.datasource.url=jdbc:postgresql://payment-db:5432/paymentdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
