spring.application.name=payment-service
server.port=4011

# Stripe Configuration
stripe.webhook.secret=
stripe.api.key=

# Database Configuration
spring.datasource.url=jdbc:postgresql://payment-db:5432/paymentdb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
